version: "3.8"

services:
  direnv-backup-with-dev-deps:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: direnv-backup-with-dev-deps
    container_name: direnv-backup-with-dev-deps
    command: fish

    volumes:
      # mount only source files
      - "./direnv_backup:/app/direnv_backup"
      - "./tests:/app/tests"
      - "./devex:/app/devex"
      - "./pyproject.toml:/app/pyproject.toml"
      - "./setup.cfg:/app/setup.cfg"
      - "./LICENSE:/app/LICENSE"
      - "./README.md:/app/README.md"

    environment:
      - PYTHONBREAKPOINT=ipdb.set_trace

  direnv-backup-only-pkgbuild:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: direnv-backup-only-pkgbuild
    container_name: direnv-backup-only-pkgbuild

    volumes:
      - "./scripts/in_container:/app"
      - "${PWD}/PKGBUILD:/pacman_build_dir/PKGBUILD"
